name: CI

on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [master, development]

jobs:
  test:
    uses: TiagoMadeira/tokio_reusable_workflows/.github/workflows/test_python_app.yaml@v1
    with:
      python-version: "3.12.3"
  
  build-push:
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: Extract metadata
        shell: bash
        run: |
          echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
          echo "branch_tag =${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
          echo "short_sha=$(echo $GITHUB_SHA | cut -c1-7)" >> $GITHUB_OUTPUT
        id: extract_metadata

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ vars.DOCKER_USERNAME }}/${{ vars.DOCKERHUB_REPOSITORY}}
          tags: |
            ${{steps.extract_metadata.outputs.branch}}
            ${{steps.extract_metadata.outputs.branch_tag}}
            ${{steps.extract_metadata.outputs.short_sha}}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        uses: docker/build-push-action@v6
        with:
          push: ${{ github.event_name != 'pull_request' }}
          tags:  ${{ steps.meta.outputs.tags }}
          file: dockerfile

    needs: [test]
